Added entries for ZWyvern and Nardovern
Mattshark89/OpenFlight-VRC pull request #15
Opened 2023-04-25 03:43 UTC by madkat

Added entries for both the [ZWyvern](https://morghus.gumroad.com/l/zwyvern) and [Nardovern](https://morghus.gumroad.com/l/nardovern) by Morghus. These are publicly available edits of the [ZDragon](https://zephyxus.gumroad.com/l/zdragon) and [Nardoragon](https://nardoiri.gumroad.com/l/Nardoragon) that integrate wings into the arms.

2023-04-25 04:43 UTC, jennytoo commented
Do these share the armatures with the ZDragon and Nardoragon, or do they have distinct armatures?

2023-04-25 05:02 UTC, madkat commented
They are distinct armatures with unique hash values. The fingers are the bones in the wings on the wyvern variants.

2023-04-25 14:10 UTC, Happyrobot33 requested changes
Just need to make sure these are v2 hashes, other than that looks good

2023-04-25 16:11 UTC, madkat commented on Packages/com.mattshark.openflight/Runtime/data.json
> +        "Hash": ["1257052648"],
My mistake! I'll update to 1.2.7 later today and get the v2 hashes.

2023-04-26 01:17 UTC, madkat commented on Packages/com.mattshark.openflight/Runtime/data.json
> +        "Hash": ["1257052648"],
Replaced v1 hashes with v2 hashes.

2023-04-26 01:17 UTC, madkat commented on Packages/com.mattshark.openflight/Runtime/data.json
> +        "Hash": ["1318433413"],
Replaced v1 hashes with v2 hashes.

2023-04-26 01:39 UTC, Happyrobot33 approved these changes

2023-04-26 01:40 UTC, merged