Match data.json location to Udon
Mattshark89/OpenFlight-VRC pull request #31
Opened 2023-05-25 05:51 UTC by kitlith

This is the URL that the system is trying to query for data.json:
https://github.com/Mattshark89/OpenFlight-VRC/blob/683a0b093c24d67aceeb563928f3b7cf3a87f549/Packages/com.mattshark.openflight/Runtime/Scripts/Detection/AvatarListLoader.cs#L12-L13

This is the URL I was actually able to find data.json at: https://mattshark89.github.io/OpenFlight-VRC/data.json

This PR relocates the file to match where the Udon script is looking, my test shows up at https://kitl.pw/OpenFlight-VRC/Assets/OpenFlight-VRC/data.json

Grain of salt, I've not tested this PR in-game myself yet, because I didn't feel like throwing together a world to upload to test this.

2023-05-25 11:32 UTC, Happyrobot33 commented
This is actually just purely an issue because I never updated the source code to reference the root data.json location that was introduced. The prefab has the URL set appropriately
![image](https://github.com/Mattshark89/OpenFlight-VRC/assets/32679887/eadb6036-8739-46d1-b96a-149897710458)

I Would suggest just changing this PR to defining the VRCUrl to the new correct one in the source code. Alongside that, the action changes suggested would break all existing worlds since it wouldnt be putting the data,json to the root of the website anymore. As for not using the copy-action and instead just using bash, im split on this. yes it would probably make the action run faster, but im not sure it would error the action if the copy fails anymore

2023-05-25 11:32 UTC, Happyrobot33 requested changes
This is actually just purely an issue because I never updated the source code to reference the root data.json location that was introduced. The prefab has the URL set appropriately
![image](https://github.com/Mattshark89/OpenFlight-VRC/assets/32679887/eadb6036-8739-46d1-b96a-149897710458)

I Would suggest just changing this PR to defining the VRCUrl to the new correct one in the source code. Alongside that, the action changes suggested would break all existing worlds since it wouldnt be putting the data,json to the root of the website anymore. As for not using the copy-action and instead just using bash, im split on this. yes it would probably make the action run faster, but im not sure it would error the action if the copy fails anymore

2023-05-26 07:15 UTC, kitlith commented
sorry for slow reply, and for not realizing that there was a different place to specify the url!

would it be acceptable to put the json in both locations, just in case?

errors *should* still register, but i'd be willing to make sure of that, once i have time again.

2023-06-04 03:24 UTC, kitlith commented
> you technically could, but I don't really see the point of doing this since no live systems right now should be using that URL
You probably have a better idea of how this prefab has spread than I do, so I'll take your word for it. I'm just used to seeing older versions of a prefab floating around worlds, and was thus advocating for making all URLs that were ever checked for the data json available on the website.

In that case, these is no point changing the copy action, since I only switched away because of needing to create the parent directory (and even then I suppose I could have split that into a step creating the parent directory and then using the copy action), so all this PR now does is edit the URL in udon source.

... I should probably actually open the repo from within unity so that the SerializedUdonAsset updates if needed, and commit that as well, shouldn't I.

> @kitlith any update on this?
Apologies for the delay. I've not had a ton of extra time the past couple weeks, and this took a lower priority than anything else once I realized that what I had noticed wasn't actually indicating that things were broken.

2023-06-05 13:09 UTC, merged